# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

url: https://interloop.ai
enforce_ssl: interloop.ai
title: Interloop | Sales Forecasting & Intelligence Platform
email: hi@interloop.ai
description: "Sales Forecasting & Intelligence Platform"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: interloophq
github_username:  interloophq

# Build settings
markdown: kramdown

gems: [
    'jekyll-sitemap',
    'octopress-autoprefixer'
]


include: [
   '.well-known'
]