# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Interloop | Sales Execution Platform
email: hi@interloop.io
description: "Sales Execution powered by IBM Watson"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://interloop.io" # the base hostname & protocol for your site
twitter_username: interloop_io
github_username:  interloophq

# Build settings
markdown: kramdown
